 
language: node_js
os:
  - osx
  - linux
node_js: 8

before_install:
  - export PATH=/opt/ghc/8.8.3/bin:$PATH

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - |
    echo ">>> Run integration tests"
    npm install && npm test

after_success:
  - npm run coverage

cache: npm

addons:
  apt:
    sources:
    - hvr-ghc    
    packages:
    - libsecret-1-dev
    - ghc-8.8.3    
  homebrew:
    packages:
    - ghc@8.8
    update: true
