 
language: node_js
os:
  - osx
  - linux
node_js: 8

before_install:
  - |
    # install stack
    curl -sSL https://get.haskellstack.org/ | sh

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - |
    echo ">>> Run integration tests"
    yarn && yarn compile && yarn test

after_success: yarn run coveralls

cache: yarn

addons:
  apt:
    packages:
    - libsecret-1-dev
