name: branch

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: { CODE_VERSION: 'stable' }
    steps:
    - uses: actions/checkout@v2

    - name: Setup GHC environment
      run: echo "/opt/ghc/bin" >> $GITHUB_PATH

    - run: npm install

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm test

    - name: Add GHC extension output (on failure)
      if: failure()
      run: find .vscode-test/vscode-*/udd/logs -name *GHC* -exec cat {} \;
