name: master

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        env:
          - { CODE_VERSION: 1.38.0 }
          - { CODE_VERSION: 'stable' }
    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup GHC environment
      run: echo "/opt/ghc/bin" >> $GITHUB_PATH

    - run: npm install

    - name: Run tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm test

    - name: Add GHC extension output (on failure on Linux)
      if: failure() && runner.os == 'Linux'
      run: find .vscode-test/vscode-*/udd/logs -name *GHC* -exec cat {} \;

    - name: Add GHC extension output (on failure on Windows)
      if: failure() && runner.os == 'Windows'
      run: Get-ChildItem -Path .vscode-test -Include *GHC.log -File -Recurse | Get-Content

  metrics:
    runs-on: ubuntu-latest
    env: { CODE_VERSION: 1.48.0 }
    steps:
    - uses: actions/checkout@v2

    - name: Setup GHC environment
      run: echo "/opt/ghc/bin" >> $GITHUB_PATH

    - run: npm install

    - name: Run tests with coverage
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run coverage

    - name: Publish coverage on Coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: .coverage/lcov.info
